// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_WORK   Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_MOBILE Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "WORK",
	1: "HOME",
	2: "MOBILE",
}
var Person_PhoneType_value = map[string]int32{
	"WORK":   0,
	"HOME":   1,
	"MOBILE": 2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age     int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	EmailID string `protobuf:"bytes,3,opt,name=emailID" json:"emailID,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmailID() string {
	if m != nil {
		return m.EmailID
	}
	return ""
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,4,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,5,opt,name=type,enum=main.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_WORK
}

type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "main.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "main.AddressBook")
	proto.RegisterEnum("main.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0x66, 0xbb, 0xda, 0x89, 0x48, 0x9c, 0x43, 0x59, 0x3c, 0x85, 0xe0, 0x21, 0x28,
	0xe4, 0xd0, 0xfe, 0x02, 0x8b, 0x05, 0x8b, 0xd6, 0xd4, 0x45, 0xf0, 0xbc, 0xa1, 0x83, 0x96, 0x36,
	0x3b, 0x4b, 0x52, 0x0f, 0xfd, 0x87, 0xfe, 0x2c, 0xc9, 0x36, 0x4a, 0x6f, 0xdf, 0xdb, 0x7d, 0xc3,
	0xbc, 0x37, 0x70, 0x6d, 0xd7, 0xeb, 0x86, 0xda, 0xb6, 0x62, 0xde, 0x16, 0xbe, 0xe1, 0x3d, 0xa3,
	0xac, 0xed, 0xc6, 0x65, 0x3f, 0x02, 0xd4, 0x8a, 0x9a, 0x96, 0x1d, 0x22, 0x48, 0x67, 0x6b, 0xd2,
	0x22, 0x15, 0xf9, 0xc8, 0x04, 0xc6, 0x04, 0x22, 0xfb, 0x49, 0x7a, 0x90, 0x8a, 0x7c, 0x68, 0x3a,
	0x44, 0x0d, 0xe7, 0x54, 0xdb, 0xcd, 0x6e, 0xf1, 0xa8, 0xa3, 0x60, 0xfc, 0x93, 0x37, 0x6f, 0x10,
	0xaf, 0xbe, 0xd8, 0xd1, 0xeb, 0x77, 0x5d, 0x51, 0x83, 0x63, 0x50, 0x2e, 0x90, 0x96, 0xc1, 0xd7,
	0x2b, 0xbc, 0x03, 0xb9, 0x3f, 0x78, 0xd2, 0xc3, 0x54, 0xe4, 0x57, 0x93, 0x71, 0xd1, 0xc5, 0x28,
	0x8e, 0x11, 0x8a, 0x30, 0xff, 0x7e, 0xf0, 0x64, 0x82, 0x27, 0xbb, 0x87, 0xd1, 0xff, 0x13, 0x5e,
	0x80, 0xfc, 0x28, 0xcd, 0x73, 0x72, 0xd6, 0xd1, 0x53, 0xb9, 0x9c, 0x27, 0x02, 0x01, 0xd4, 0xb2,
	0x9c, 0x2d, 0x5e, 0xe6, 0xc9, 0x20, 0x9b, 0x42, 0xfc, 0x70, 0x6c, 0x39, 0x63, 0xde, 0xe2, 0x2d,
	0x28, 0x4f, 0xec, 0x77, 0x5d, 0xa1, 0x28, 0x8f, 0x27, 0x97, 0xa7, 0x9b, 0x4c, 0xff, 0x57, 0xa9,
	0x70, 0x8c, 0xe9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xac, 0xaf, 0x0e, 0x21, 0x01, 0x00,
	0x00,
}
